services:
  caitlyn:
    image: skillsharp123/skillsharp-fe:v1.0.11
    ports:
      - "3000:5173"
    env_file:
      - ./configs/Caitlyn/.env
    networks:
      - my_network

  envoy:
    image: envoyproxy/envoy:v1.24-latest
    ports:
      - "9901:9901"
      - "8081:8081"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - my_network
    depends_on:
      akali:
        condition: service_started
      thresh:
        condition: service_started
      questionai:
        condition: service_started

  akali:
    build:
      context: ./raw_services/Akali
      dockerfile: dockerfile
    env_file:
      - ./configs/Akali/.env
    networks:
      - my_network
    depends_on:
      database:
        condition: service_started

  thresh:
    image: skillsharp123/skillsharp_thresh:v1.0.6
    env_file:
      - ./configs/Thresh/.env
    networks:
      - my_network
    depends_on:
      database:
        condition: service_started

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: skillsharp@fit!2021
    networks:
      - my_network
    ports:
      - "3306:3306"
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "${ELASTIC_PORT:-9200}:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - my_network

  questionai:
    build:
      context: ./raw_services/QuestionGenerator
      dockerfile: Dockerfile
    env_file:
      - ./configs/QuestionGenerator/.env
    depends_on:
      - elasticsearch
    networks:
      - my_network

networks:
  my_network:

volumes:
  elasticsearch_data: